"""add_patient_profiles_and_doctor_patient_relations

Revision ID: 122b534a88c6
Revises: d51acd2a3357
Create Date: 2026-07-14 10:47:41.982828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122b534a88c6'
down_revision: Union[str, None] = 'd51acd2a3357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patient_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='医生用户ID'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='病人用户ID'),
    sa.Column('relation_status', sa.String(length=20), nullable=True, comment='active / inactive'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('assigned_by', sa.Integer(), nullable=True, comment='分配者（管理员）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='关联时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_relations_doctor_id'), 'doctor_patient_relations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_relations_patient_id'), 'doctor_patient_relations', ['patient_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户账号'),
    sa.Column('patient_code', sa.String(length=50), nullable=False, comment='患者编号'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='Male / Female / Unknown'),
    sa.Column('birth_date', sa.DateTime(), nullable=True, comment='出生日期'),
    sa.Column('id_card_hash', sa.String(length=64), nullable=True, comment='身份证号哈希'),
    sa.Column('blood_type', sa.String(length=5), nullable=True, comment='血型'),
    sa.Column('height_cm', sa.Float(), nullable=True, comment='身高 cm'),
    sa.Column('weight_kg', sa.Float(), nullable=True, comment='体重 kg'),
    sa.Column('allergies', sa.Text(), nullable=True, comment='过敏史'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='就诊科室'),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True, comment='紧急联系人'),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True, comment='紧急联系电话'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_patient_code'), 'patient_profiles', ['patient_code'], unique=True)
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_index(op.f('ix_patient_profiles_patient_code'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_doctor_patient_relations_patient_id'), table_name='doctor_patient_relations')
    op.drop_index(op.f('ix_doctor_patient_relations_doctor_id'), table_name='doctor_patient_relations')
    op.drop_table('doctor_patient_relations')
    # ### end Alembic commands ###
