"""upgrade: change min training expoches to 10, change model_name

Revision ID: 1a6ce5b49d0e
Revises: 21dfa8dc0aeb
Create Date: 2026-07-16 09:58:49.649736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6ce5b49d0e'
down_revision: Union[str, None] = '21dfa8dc0aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               comment='模型类型：yolo11n/s/m/l/x',
               existing_comment='模型类型：yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('training_tasks', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='基础模型：yolo11n/s/m/l/x',
               existing_comment='基础模型：yolov11n/s/m/l/x',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_tasks', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='基础模型：yolov11n/s/m/l/x',
               existing_comment='基础模型：yolo11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               comment='模型类型：yolov11n/s/m/l/x',
               existing_comment='模型类型：yolo11n/s/m/l/x',
               existing_nullable=True)
    # ### end Alembic commands ###
