"""extend_detection_tasks_with_patient_profile

Revision ID: 21dfa8dc0aeb
Revises: dfdf4d9e152b
Create Date: 2026-07-14 10:53:08.816854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21dfa8dc0aeb'
down_revision: Union[str, None] = 'dfdf4d9e152b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_tasks', sa.Column('patient_profile_id', sa.Integer(), nullable=True, comment='关联患者档案'))
    op.add_column('detection_tasks', sa.Column('cxr_image_id', sa.Integer(), nullable=True, comment='关联胸片影像记录（cxr_images 表待建）'))
    op.add_column('detection_tasks', sa.Column('referenced_record_ids', sa.JSON(), nullable=True, comment='LLM 分析时引用的历史病例 ID 列表'))
    op.create_index(op.f('ix_detection_tasks_cxr_image_id'), 'detection_tasks', ['cxr_image_id'], unique=False)
    op.create_index(op.f('ix_detection_tasks_patient_profile_id'), 'detection_tasks', ['patient_profile_id'], unique=False)
    op.create_foreign_key(None, 'detection_tasks', 'patient_profiles', ['patient_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_detection_tasks_patient_profile_id'), table_name='detection_tasks')
    op.drop_index(op.f('ix_detection_tasks_cxr_image_id'), table_name='detection_tasks')
    op.drop_column('detection_tasks', 'referenced_record_ids')
    op.drop_column('detection_tasks', 'cxr_image_id')
    op.drop_column('detection_tasks', 'patient_profile_id')
    # ### end Alembic commands ###
