"""add_user_type_to_users

Revision ID: d51acd2a3357
Revises: a50079ca061d
Create Date: 2026-07-14 10:45:40.167454

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d51acd2a3357"
down_revision: Union[str, None] = "a50079ca061d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先添加为可空列
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            sa.String(length=20),
            nullable=True,
            comment="用户类型：admin / doctor / patient",
        ),
    )
    # 2. 给已有数据填充默认值
    op.execute("UPDATE users SET user_type = 'patient' WHERE user_type IS NULL")
    # 3. 设为不可空
    op.alter_column("users", "user_type", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###
