"""add_medical_records_and_attachments

Revision ID: dfdf4d9e152b
Revises: 122b534a88c6
Create Date: 2026-07-14 10:51:46.932235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdf4d9e152b'
down_revision: Union[str, None] = '122b534a88c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False, comment='所属患者'),
    sa.Column('record_uuid', sa.String(length=100), nullable=False, comment='病例唯一标识'),
    sa.Column('record_type', sa.String(length=30), nullable=True, comment='outpatient / inpatient / follow_up / emergency'),
    sa.Column('chief_complaint', sa.Text(), nullable=True, comment='主诉'),
    sa.Column('present_illness', sa.Text(), nullable=True, comment='现病史'),
    sa.Column('past_history', sa.Text(), nullable=True, comment='既往史'),
    sa.Column('family_history', sa.Text(), nullable=True, comment='家族史'),
    sa.Column('physical_examination', sa.Text(), nullable=True, comment='体格检查'),
    sa.Column('auxiliary_exams', sa.JSON(), nullable=True, comment='辅助检查结果'),
    sa.Column('diagnosis', sa.JSON(), nullable=True, comment='诊断结论列表'),
    sa.Column('treatment_plan', sa.Text(), nullable=True, comment='治疗方案'),
    sa.Column('prescription', sa.JSON(), nullable=True, comment='处方信息'),
    sa.Column('doctor_notes', sa.Text(), nullable=True, comment='医生备注'),
    sa.Column('record_status', sa.String(length=20), nullable=True, comment='draft / completed / reviewed'),
    sa.Column('visit_date', sa.DateTime(), nullable=True, comment='就诊日期'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建医生'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最后编辑者'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_patient_profile_id'), 'medical_records', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_medical_records_record_uuid'), 'medical_records', ['record_uuid'], unique=True)
    op.create_table('medical_record_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='所属病例'),
    sa.Column('attachment_type', sa.String(length=20), nullable=False, comment='cxr_image / lab_report / prescription / other'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('minio_path', sa.String(length=500), nullable=False, comment='MinIO 路径'),
    sa.Column('minio_url', sa.String(length=500), nullable=True, comment='预签名 URL'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME 类型'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='附件描述'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='上传人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_record_attachments_record_id'), 'medical_record_attachments', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_record_attachments_record_id'), table_name='medical_record_attachments')
    op.drop_table('medical_record_attachments')
    op.drop_index(op.f('ix_medical_records_record_uuid'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_patient_profile_id'), table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###
